name: flutter_figma_generator
description: Generate color classes, font styles, shadows and dimens from figma, use design system to preview generated classes and widgets.
version: 1.0.3

homepage: https://github.com/Iteo/figma-generator
repository: https://github.com/Iteo/figma-generator
issue_tracker: https://github.com/Iteo/figma-generator/issues
documentation: https://github.com/Iteo/figma-generator

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: '>=3.0.0'

dependencies:
  analyzer: ^5.0.0
  args: ^2.3.1
  flutter:
    sdk: flutter
  meta: ^1.7.0
  path: ^1.8.1
  flutter_hooks: ^0.18.5+1
  path_provider: ^2.0.11
  flutter_svg: ^1.0.0
  yaml: ^3.1.1
  sliver_tools: ^0.2.8
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
