name: figma_generator
description: Styles generator from figma & Design System
version: 1.0.1

homepage: https://github.com/Iteo/figma-generator
repository: https://github.com/Iteo/figma-generator
issue_tracker: https://github.com/Iteo/figma-generator/issues
documentation: https://github.com/Iteo/figma-generator

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: '>=3.0.0'

dependencies:
  analyzer: ^5.0.0
  args: ^2.3.1
  flutter:
    sdk: flutter
  json_annotation: ^4.6.0
  meta: ^1.7.0
  path: ^1.8.1
  flutter_hooks: ^0.18.5+1
  path_provider: ^2.0.11
  flutter_svg: ^1.0.0
  yaml: ^3.1.1
  sliver_tools: ^0.2.8

dev_dependencies:
  build_runner: ^2.2.1
  flutter_lints: ^2.0.1
  json_serializable: ^6.3.2
  flutter_test:
    sdk: flutter